### ISSUE TITLE
Make Variable class not sealed

### ISSUE THREAD

**Issue by KarloX2** [lextm/sharpsnmplib#38]
Hi!

Would you mind removing the sealed keyword from the Variable class? I would like to store additional properties with it. Also, can you make the setter of the Data property of that class public?

Thanks

**Comment by lextm** [comment]
All sealed classes are sealed because they just match the protocol definitions. What kind of additional data do you plan to store? You should try other approaches without modifying this class.

**Comment by KarloX2** [comment]
For a number of (historical) reasons, I have my own MIB catalog and objects representing each node/scalar/column etc. in my mib. I like to have a reference back from the Variable to the MIB object, that's why I'm asking. By sub-classing Variable I would not affect the protocol consistency. IMHO, there are always numerous options to stop a software from working properly and sealing classes is only a very little help to avoid that, at the cost of flexibility.

As for the other question: I'd like to instanciate Variable objects and assign the Data later, that's why I'm asking to make the Data property public-set.

Thanks

**Comment by lextm** [comment]
For the MIB reference part, #SNMP Library is designed to work with the paid #SNMP Pro. #SNMP Pro parses the documents and hold a central registry for OIDs. So currently no plan to modify Variable in any way. You can create a fork on your own if you like.

For the Data part, there is no setter because all such classes are immutable.

**Comment by KarloX2** [comment]
Ok. Thanks.
