### ISSUE TITLE
SnmpEngine.Stop can hang on macOS if .NET Core is used

### ISSUE THREAD

**Issue by lextm** [lextm/sharpsnmplib#52]
Like the unit test cases show, `SnmpEngine.Stop` should not be called on .NET Core if running on macOS. Debugging the details shows a `Socket.Dispose` related hang. The cause is not yet known.

**Comment by aib** [comment]
This is an issue with .NET Core on non-Windows systems (Linux seems to be affected as well).

The problem is that `Socket.Dispose()` (called by `Socket.Close()`) does not interrupt `Socket.ReceiveFrom()` calls, hanging receiving threads as well as blocking itself.

I have added a PR (#65) which works around this by calling `Socket.Shutdown()`. The call raises an exception, but interrupts `ReceiveFrom()` calls even so, allowing `Dispose()` (and the receive call) to complete and the socket to unbind.

POSIX requires a shutdown(2) call to interrupt recv(2)/recvfrom(2) as well; that parallel might make this workaround less ugly.

**Comment by lextm** [comment]
I just did some testing, and the exception itself seems to be reasonable (Socket Error Code: NotConnected).

**Comment by lextm** [comment]
Closed via #65
